name: gebaude_manager
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  image_picker: ^1.0.7
  pdf: ^3.10.8
  path_provider: ^2.1.2
  printing: ^5.12.0
  file_picker: ^6.1.1
  open_filex: ^4.4.0
  leak_tracker: 10.0.0
  leak_tracker_flutter_testing: 2.0.1
  leak_tracker_testing: 2.0.1
  meta: 1.11.0
  pdf_widget_wrapper: 1.0.3
  test_api: 0.6.1
  vm_service: 13.0.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true